[package]
name = "ram-observer-rs"
version = "1.1.0"
edition = "2021"
license = "MIT"
authors = ["Shifty <contact@shifty.cloud>"]

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
sysinfo = "0.32.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
zip = "2.2.0"