name: Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Get Version
        id: get_version
        run: |
          $version = (Select-String -Path Cargo.toml -Pattern '^version = "(.*?)"').Matches.Groups[1].Value
          echo "version=$version" >> $env:GITHUB_OUTPUT
          
      - name: Build Release
        run: cargo build --release
        
      - name: Create ZIP
        run: |
          cd target/release
          7z a ../../ram-observer-windows.zip ram-observer-rs.exe
          cd ../..
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ram-observer-windows.zip
          generate_release_notes: true
          tag_name: v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
